### ISSUE TITLE
Improvement in code

### ISSUE THREAD

**Issue by paperboy6891** [paperboy6891/Final-Project#1]
Can someone tell me how i can improve the code written in script js ?
Before making pull request do tell me what suggetions you have so i can review.
Thank You!

**Comment by arhmAli** [comment]
1. Convert the regular function expression to arrow function.
2. Convert the vars to let just QOL improvement
3. The main thing which effects the performance of your code is not using for loop in these cases you can use a lot of arrays methods like reduce and forEach which will help the O(n) to get better and compilation time will be much lowered!

**Comment by paperboy6891** [comment]
ok you can submit a PR and i will merge it thank you for your time !

**Comment by arhmAli** [comment]
ok
